Error: creating EFS Mount Target
Error: creating EFS Mount Target (fs-010d86ed2d4efb31f): AccessDeniedException: User is not authorized to perform that action on the specified resource
195│ status code: 403, request id: 87a44e26-6c51-4378-a94f-a14b0d251eb5
196│
197│ with aws_efs_mount_target.media_a,
198│ on efs.tf line 27, in resource "aws_efs_mount_target" "media_a":
199│ 27: resource "aws_efs_mount_target" "media_a" {
200│
201╵
202╷
203│ Error: creating EFS Mount Target (fs-010d86ed2d4efb31f): AccessDeniedException: User is not authorized to perform that action on the specified resource
204│ status code: 403, request id: 946cb16a-359b-497b-8518-eaaae13fcb47
205│
206│ with aws_efs_mount_target.media_b,
207│ on efs.tf line 33, in resource "aws_efs_mount_target" "media_b":
208│ 33: resource "aws_efs_mount_target" "media_b" {

I was able to fix it by following these steps:

1) Add "ec2:DescribeNetworkInterfaceAttribute" to the list of actions in data "aws_iam_policy_document" "efs" { inside iam.tf.

2) Then I ran docker compose run --rm terraform -chdir=setup apply to effect the action in step 1.



The reason for this is that "elasticfilesystem:DescribeMountTargetSecurityGroups" depends on the "ec2:DescribeNetworkInterfaceAttribute" action.

https://wex.udemy.com/course/devops-deployment-automation-terraform-aws-docker/learn/lecture/43791232#questions/21867826